<?php

namespace AppBundle\Entity;

/**
 * AnswersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AnswersRepository extends \Doctrine\ORM\EntityRepository
{
	public function saveAnswer($params)
	{
		if(!is_array($params) || count($params) < 1) {
			return false;
		}

		$em = $this->getEntityManager();

		$answer = new Answers();
		$answer->setArticleId($params['article_id']);
		$answer->setArticleAnswer($params['answer']);
		$answer->setCreatedOn(new \DateTime());

		$em->persist($answer);
		$em->flush();

		return true;
	}

	public function getAnswersByArticle($articleId)
	{
		$return = false;
		if(!$articleId || $articleId < 1) {
			return $return;
		}

		$answers = $this->findBy(array(
			'articleId' => $articleId
			));
		if($answers != null) {
			foreach($answers as $v) {
				$return[] = array(
					'answer' => $v->getArticleAnswer(),
					'created_on' => $v->getCreatedOn()->format('jS F Y @ H:i')
					);
			}
		}

		return $return;
	}
}
