<?php

namespace AppBundle\Entity;

/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleRepository extends \Doctrine\ORM\EntityRepository
{
	protected $classTable = 'AppBundle:Article';
	/**
	 * Creates a new article
	 * @param  array  $params holds the parameters to be inserted (int author_id, text $article)
	 * @return boolean
	 */
	public function createArticle($params=array())
	{
		if(!is_array($params) || count($params) < 1) {
			return false;
		}

		$em = $this->getEntityManager();

		$article = new Article();
		$article->setArticleText($params['article']);
		$article->setAuthorId($params['author_id']);
		$article->setCreatedOn(new \DateTime());

		$em->persist($article);
		$em->flush();

		return true;
	}

	/**
	 * gets the author id for the given article
	 * @param  int $articleId The article Id
	 * @return mixed          False on error, int on success
	 */
	public function getAuthorId($articleId)
	{
		$return = false;
		if(!isset($articleId) || $articleId < 1) {
			return $return;
		}

		$em = $this->getEntityManager();
		
		$getAuthor = $em->findOneById($articleId);
		if(!is_null($getAuthor))
		{
			$return = $getAuthor->getAuthorId();
		}

		return $return;
	}

	public function getFullArticle($articleId)
	{
		$return = false;
		if(!isset($articleId)) {
			return $return;
		}

		$em = $this->getEntityManager();

		$query = $em->createQuery('
			SELECT a FROM '.$this->classTable.'
			WHERE id = :articleId
			LEFT JOIN answers an
			ON an.articleId = a.id
			');
	}
}
