<?php

namespace AppBundle\Entity;

/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleRepository extends \Doctrine\ORM\EntityRepository
{
	public function insertData($params=array())
	{
		if(!is_array($params) || count($params) < 1) {
			return false;
		}

		$em = $this->getEntityManager();

		$article = new Article();
		$article->setArticleText($params['article']);
		$article->setAuthorId($params['author_id']);
		$article->setCreatedOn(new \DateTime());

		$em->persist($article);
		$em->flush();

		return true;
	}
}
