<?php

namespace AppBundle\Entity;

/**
 * RatingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RatingRepository extends \Doctrine\ORM\EntityRepository
{
	public function saveRating($params)
	{
		if(!is_array($params) || count($params) < 1) {
			return false;
		}

		$em = $this->getEntityManager();

		$rating = new Rating();
		$rating->setArticleId($params['article_id']);
		$rating->setStarRating($params['rating']);
		$rating->setCreatedOn(new \DateTime());

		$em->persist($rating);
		$em->flush();

		return true;
	}
}
